### ISSUE TITLE
Name of library and repository

### ISSUE THREAD

**Issue by atgeirr** [Statoil/libecl#100]
From the repository name (and also some other communication) I had the impression that the name of this library was `libecl`. Apparently the intent is that the name should be `ecl`, I would then propose that the name of the repository is changed to ecl, too. Since that has some annoying consequences perhaps it could also be considered to make `libecl` the official, communicated, name of the library.

The situation I fear is something like this: I specify "LIBECL_LIBRARY" but that is not used, instead "ECL_LIBRARY" is used and resolved to something different. I then get link errors or (worse) incorrect results I cannot understand. To avoid such problems it must be clear which name to use.

**Comment by pgdr** [comment]
That's a good point, and the `libecl` is actually just the name of the `c` target.  A renaming to `ecl` is not a bad idea.

**Comment by atgeirr** [comment]
Others have also suggested `eclio` as the name for the library, I don't know if that is on the table but I'll leave further discussion to you guys.

**Comment by pgdr** [comment]
`eclio` will not be considered, no.

**Comment by markusdregi** [comment]
Thank you for your suggestions.
