### ISSUE TITLE
Problem with multiprocessing.

### ISSUE THREAD

**Issue by joakim-hove** [Statoil/libecl#116]
See : https://github.com/Ensembles/ert/issues/1498

**Comment by joakim-hove** [comment]
The problem is that the multiprocessing is based on *process-based* parallellism, and the Python objects are passed from child process to parent through Python pickle functionality - that does not (and can not) carry over the pointers to the underlying C structures - that is way it crashes.

To achieve your goal you would have to use *thread based parallelism* - slightly more complex, but perfectly doable. Might be able to assist you with later, but not right now.

**Comment by wouterjdb** [comment]
Ok, I'm going to give this a try.

**Comment by wouterjdb** [comment]
Instead of 

`from multiprocessing import Pool`

I used

`from multiprocessing.pool import ThreadPool as Pool`

in combination with the code I supplied in the original Issue.

This works and gives some speed improvements. Thanks for the tip.

**Comment by pgdr** [comment]
I'm closing this as I can't see any concrete issue to fix.

Please reopen and rewrite the issue if there still is one.
