### ISSUE TITLE
Duplicate Preprocessor Symbol INTEHEAD_NXWELZ_INDEX in ecl_kw_magic.h

### ISSUE THREAD

**Issue by bska** [Statoil/libecl#138]
Commit 361b2c904 introduced
```C
#define INTEHEAD_NXWELZ_INDEX 26
```
into [`ecl_kw_magic.h`](https://github.com/Statoil/libecl/commit/361b2c90494a1eaede3e964b55097abb7cf011f7#diff-0c7a30e73cd7bbb17c1b18d8d17563b1R386). However the symbol already [existed](https://github.com/Statoil/libecl/blob/master/lib/include/ert/ecl/ecl_kw_magic.h#L404) in said file.  While not really an error (the definitions are commensurate), it is probably best to remove one of the definitions.

**Comment by pgdr** [comment]
Thanks for the issue, this will be fixed in #139.

**Comment by pgdr** [comment]
fixed in #139.
