### ISSUE TITLE
CMake errors out when requesting static libs even if python is not available

### ISSUE THREAD

**Issue by blattms** [Statoil/libecl#16]
I do not have the requested python version on my system. Nevertheless CMake issues an error when run with -DBUILD_SHARED_LIBS=OFF
```
CMake Error at CMakeLists.txt:140 (message):
  The Python wrappers require shared libraries


-- Configuring incomplete, errors occurred!

**Comment by joakim-hove** [comment]
Thank you - will look into.

**Comment by markusdregi** [comment]
You should disable python if you want to run it without Python. Please reopen if you need any further assistance.
