### ISSUE TITLE
Import of index file on Windows

### ISSUE THREAD

**Issue by magnesj** [Statoil/libecl#165]
I have started testing how to use the keyword index file on Windows. Export of this index file seems to be OK, but import failed.

For my test case, no data was read at the following location:
https://github.com/Statoil/libecl/blob/master/lib/ecl/ecl_file_kw.c#L359

**Comment by joakim-hove** [comment]
> I have started testing how to use the keyword index file on Window

Does it work on Linux?

> For my test case, no data was read at the following location:

What is the value of `buffer_size` and `num`?

**Comment by joakim-hove** [comment]
Try passing `"rb"` to the open call here: https://github.com/Statoil/libecl/blob/master/lib/ecl/ecl_file.c#L1027?

**Comment by magnesj** [comment]
It works as expected on Linux

**Comment by joakim-hove** [comment]
> It works as expected on Linux

OK - good.

**Comment by magnesj** [comment]
> Try passing "rb" to the open call here: https://github.com/Statoil/libecl/blob/master/lib/ecl/ecl_file.c#L1027?
> 
> And "wb" here: https://github.com/Statoil/libecl/blob/master/lib/ecl/ecl_file.c#L1016

Using "rb" and "wb" seems to fix the issue on Windows.

**Comment by joakim-hove** [comment]
> Using "rb" and "wb" seems to fix the issue on Windows.

OK - cool!

**Comment by magnesj** [comment]
See #166
