### ISSUE TITLE
Read out report number from restart files starting with lower case in file extension

### ISSUE THREAD

**Issue by magnesj** [Statoil/libecl#303]
A user of ResInsight has reported issues reading restart files using lower case in the file extension, 
`*.x0001` does not load
`*.X0001` loads correctly

Can this be fixed in libecl?

https://github.com/OPM/ResInsight/issues/2241

**Comment by joakim-hove** [comment]
This can probably be fixed, but what does 'does not load' mean, as precise as possible.

**Comment by magnesj** [comment]
After a bit more debugging I have tracked down the issue to the function `ecl_util_filename_report_nr` not being able to handle lower case extensions.
