### ISSUE TITLE
problem with output summary file

### ISSUE THREAD

**Issue by Shrikantspatil** [Statoil/libecl#358]
Hello everyone !

I am new to OPM flow simulation.  I just ran the Norne case using AWS cloud.  I could open the .EGRID file in ResInsight,  but the .SMSPEC generated after the simulation is not loading in ResInsight.  Can someone please help me with this ?  

Any tips/guidance will be greatly appreciated !

Thank you,
Shri

**Comment by joakim-hove** [comment]
Post the summary file somewhere, or send it to me on joaho @ Statoil.om and we will take a look

**Comment by Shrikantspatil** [comment]
Thanks Joakim ! I just emailed you the summary file.

**Comment by joakim-hove** [comment]
> Thanks Joakim ! I just emailed you the summary file.

I got it thank you; I am sorry if this is obvious to you - but anyway: The `SMSPEC` file is only the summary *header* file - in addition you need the `UNSMRY` file which is is summary *data* file. If you only had the `SMSPEC` file available when trying to load in Resinsight that should explain why you can not load the summary results in Resinsight.

**Comment by Shrikantspatil** [comment]
awesome !! it worked.  Thank you very much for your help !  sorry I just started using OPM, so I am still figuring out stuff.

**Comment by joakim-hove** [comment]
Good to hear!
