### ISSUE TITLE
Make the ecl python wrappers work on macOS

### ISSUE THREAD

**Issue by kudhru** [Statoil/libecl#40]
Hi

Can someone explain how to make the ecl python wrappers work on macOS?

I did the following steps:
```
git clone https://github.com/Statoil/libecl.git
cd libecl
mkdir build
cd build
cmake ..
make
make install
```

And then added **libecl/python/python/ecl** to the PYTHONPATH env variable. When I try to run [summaryplot](https://raw.githubusercontent.com/OPM/opm-utilities/master/summaryplot), it gives the following error:

```
Traceback (most recent call last):
  File "Documents/partTime/reserMine/rmine-backend/extras/summaryplot", line 52, in <module>
    import ecl.ecl as ecl
  File "/Users/AkhilaRasamrtaMurthih/Documents/partTime/reserMine/setup/libecl/python/python/ecl/ecl/__init__.py", line 75, in <module>
    import ecl.util
ImportError: No module named util
```

**Comment by joakim-hove** [comment]
Thank you for trying the libecl Python wrappers - we think they are quite cool! Be aware that we are right halfways through a quite massive reorganisation of the code, so things might change quite a lot on short notice.

I actually think the `from ecl.ecl import ecl` construction in summaryplot is a victim of the mentioned reorganisation, and that you have done things correctly, will try to look into it tomorrow.

**Comment by joakim-hove** [comment]
OK: I have created a PR on opm-utilities to fix summaryplot:  https://github.com/OPM/opm-utilities/pull/19

Before it is merged you could just try to update the summaryplot script the same way.

**Comment by markusdregi** [comment]
I'm closing this one as the PR is merged in OPM. Do not hesitate to come back if you experience any further issues.
