### ISSUE TITLE
EGRID ACTNUM different from INIT/RST active cells

### ISSUE THREAD

**Issue by tpradeep** [Statoil/libecl#401]
grid = EclGrid('Eclipse.EGRID')
init = EclInitFile(grid, 'Eclipse.INIT')
permx = init['PERMX'][0]
permx3d = Ecl3DKW.castFromKW(permx, grid)

ERROR:
raise ValueError("Size mismatch - must have size matching global/active size of grid")

ACTNUM in EGRID is different from defined cells in INIT and RST files. I checked the data in Petrel. Need to modify the number of active cells based on PORV cut off. How can I do this?

**Comment by tpradeep** [comment]
Used this but it is a slow process as individual numbers are extracted,

m=0
for n in range(0,len(efile['PORV'][0])):
	if efile['PORV'][0][n]>0:
		print m,grid.get_ijk(active_index=n)[0],   grid.get_ijk(active_index=n[1],   grid.get_ijk(active_index=n)[2], rst['PRESSURE'][0][m]
		m=m+1

It gives

Active_Index(from rst file)  i  j  k  PRESSURE

**Comment by joakim-hove** [comment]
```python
grid = EclGrid('Eclipse.EGRID')
init = EclInitFile(grid, 'Eclipse.INIT')
permx = init['PERMX'][0]
```
The `permx` keyword you have extracted here is already `Ecl3DKW`  instance, so you are doing an extra - not required conversion. It should be said though the `Ecl3DKw` was a class which seemed smart at the time - but in practice the base class `EclKW` has got far more use and testing. To just a plain `EclKW`you would open the INIT file as a plain `EclFile`:

```python
init = EclFile("ECLIPSE.INIT")
permx = init["PERMX][0]
```

**Comment by joakim-hove** [comment]
> ACTNUM in EGRID is different from defined cells in INIT and RST files. I checked the data in Petrel. 

Now - that sounds like something is wrong with your simulation files. 

> Need to modify the number of active cells based on PORV cut off. How can I do this?

I don't really understand what you want to achieve; but what you do here:

```python
m=0
for n in range(0,len(efile['PORV'][0])):
if efile['PORV'][0][n]>0:
   print m,grid.get_ijk(active_index=n)[0], grid.get_ijk(active_index=n[1], grid.get_ijk(active_index=n)[2],           rst['PRESSURE'][0][m]
m=m+1
```
is to run through all the elements in the pressure field and print the active index along with (i,j,k) and the pressure. First of all - if the ACTNUM field does not agree with length of the pressure vector the approach you have taken does not solve anything - it will only mask a problem. But anyway, the way I would have written that code was:

```
rst_file = EclFile("CASE.UNRST")
pressure = rst_file["PRESSURE"][0]

for index,p in enumerate(pressure):
     ijk = grid.get_ijk(active_index = index)
     print "%d, (%d;%d;%d)   %g"  % (index, ijk[0], ijk[1], ijk[2], p)
```
roughly the same as you had - but a bit less copying and hopefully faster.

**Comment by tpradeep** [comment]
Let me share petrel statistics' screenshot tomorrow which shows the discrepancy wrt to ACTNUM

**Comment by joakim-hove** [comment]
> So how can I do this directly using grid,init and x0000 files?
```python
rst_file = EclFile("CASE.X0000")
pressure = rst_file["PRESSURE"][0]

for index,p in enumerate(pressure):
     ijk = grid.get_ijk(active_index = index)
     xyz = grid.get_xyz( active_index=inedx)
     print "%d, (%d;%d;%d)  (%g,%g,%g)  %g"  % (index, ijk[0], ijk[1], ijk[2], ,xyz[0], xyz[1], xyz[2], p)
```
> Let me share petrel statistics' screenshot tomorrow which shows the discrepancy wrt to ACTNUM. I don't see any issues loading the files in petrel. 

That sounds good - be aware that there will be a couple of days holiday here in Norway, so response might be slow.

**Comment by tpradeep** [comment]
Perfect. It works. Thanks. I understood where I was wrong.
