### ISSUE TITLE
windows python libecl Compile failure

### ISSUE THREAD

**Issue by joylin1984** [Statoil/libecl#474]
Thanks to the author, hope to improve the compatibility for windows。

windows 10
python 3.6.6
msvc 2015.3
cmake 3.12

CIL: python setup.py build

ERROR:
```
TestArea.obj : error LNK2019: unresolved external symbol _test_work_area_alloc_input_path refer
enced in function "private: class std::basic_string<char,struct std::char_traits<char>,class std:
:allocator<char> > __thiscall ERT::TestArea::inputPath(class std::basic_string<char,struct std::c
har_traits<char>,class std::allocator<char> > const &)const " (?inputPath@TestArea@ERT@@ABE?AV?$b
asic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV34@@Z) [D:\Python\Python_Learning\dh
an16opm_libecl-0.1.5\build\temp.win-amd64-3.6\Release\lib\ecl.vcxproj]
```

**Comment by joakim-hove** [comment]
Hmm - I am sorry, the setup. Py stuff is veery new and quite untested. If you can go with plain cmake that should be safer. Aldo windows does get less testing and use.

Anyway - will look into your bug.

**Comment by joylin1984** [comment]
> Hmm - I am sorry, the setup. Py stuff is veery new and quite untested. If you can go with plain cmake that should be safer. Aldo windows does get less testing and use.
> 
> Anyway - will look into your bug.

I use cmake, directly, but bug still exists, with consistent error messages. 
I think this is a  windows compatibility issues .
ECL is friendly to windows users, and more python users work on the windows platform. So, I think it makes sense to improve windows compatibility.

**Comment by joakim-hove** [comment]
The bug you report was in highly deprecated functionality anyways - so I have just removed it: https://github.com/Statoil/libecl/pull/475

**Comment by joylin1984** [comment]
> The bug you report was in highly deprecated functionality anyways - so I have just removed it: #475

thanks! I Fix somewhere, it works.
windows 10
python 3.6.6
msvc 2015.3
cmake 3.12

1、setup.py :      build_args = ['--config', cfg, '--', '-j2'] ==> build_args = ['--config', cfg, '--',]
-j2  Prompt invalid parameter
2、\lib\util\ecl_version.cpp  :
```
const char* ecl_version_get_git_commit() {
    #ifdef GIT_COMMIT
        return "Unknown git commit hash";
    #else
        return "Unknown git commit hash";
    #endif
}

const char* ecl_version_get_git_commit_short() {
    #ifdef GIT_COMMIT_SHORT
        return "Unknown git short commit hash";
    #else
        return "Unknown git short commit hash";
    #endif
}
```
**### Prior to modification the MSVC compiler prompted error C2561, function must return a value。**
**The problem should be a function named str()**

3、python\CMakeLists.txt：
cwrap dont work in python3， but it is good in python2.7，so I remove  “find_python_package(cwrap 1 ${PYTHON_INSTALL_PREFIX})”

Finally, I can compile and generate the libecl.dll successfully。
