### ISSUE TITLE
Installation problems when following the README

### ISSUE THREAD

**Issue by markusdregi** [Statoil/libecl#490]
Followed the recipe in the README and met a couple of problems..

```
[...]$ git submodule update --init pycmake
error: pathspec 'pycmake' did not match any file(s) known to git.
```

and

```
[...]$ pip install statoil_libecl --prefix=/my/location
Collecting statoil_libecl
  Could not find a version that satisfies the requirement statoil_libecl (from versions: )
No matching distribution found for statoil_libecl
```

When fetching and installing `pycmake` from github and using the `setup.py` instead of `pip`, all is good. When that is done however, `pip` gives no warnings, so it appears to be problematic only until the first install..

**Comment by joakim-hove** [comment]
OK see: https://github.com/Statoil/libecl/pull/491
