### ISSUE TITLE
How to get pressure and saturation data in each grid

### ISSUE THREAD

**Issue by hongtaoUTA** [Statoil/libecl#50]
Hi, 
I ran a case with OPM and got the well data using ecl_summary. I am wondering how can I get the pressure and saturation data in each grid, not just the well data, using python? Thank you!

**Comment by joakim-hove** [comment]
Sorry - just saw this now; will get back to you tomorrow. It is quite simple!

**Comment by hongtaoUTA** [comment]
Thank you, Joakim. I solved this problem. Yeah, it is quite simple.

**Comment by hongtaoUTA** [comment]
Hi Joakim,

I thought it is simple but it is not. I use ecl_summary filename.DATA WOPR:PROD and WWPR:PROD to get the oil and water production rate. But it seems like there is a bug. The water production rate is always the same as oil production rate, even when the water saturation is at irreducible water saturation around the production well. One possible reason is OPM or ecl_summary cannot handle very small flow rate (like 1e-3 bbl/day)? Attached is my input file. Thanks a lot!!

[Example.txt](https://github.com/Statoil/libecl/files/1008746/Example.txt)

**Comment by joakim-hove** [comment]
Hello; I am sorry for the late answer. When it comes to possible bugs in flow as a whole I fear I have less to contribute than the main developers in opm-simulators. But hopefully I can assist you somewhat when it comes to reading the binary output files using Python.

1. The class `EclFile`, or the slightly more specialized `EclRestartFile` can be used to open a file:

```
from ert.ecl import EclFile

f = EclFile("SIMULATION.UNRST")
plist = f["PRESSURE"]
```
Now `plist` is a list of `EclKW` instances with pressure data.

2. The class `EclGrid` can be used to load  a grid.
```
from ert.ecl import EclGrid

grid = EclGrid("SIMULATION.EGRID")
```
The grid object will have information about active/inactive cells, the geometry of the cells and so on. Observe that vectors you get from the restart file have length corresponding to the number of active cells, so depending on your model and what you want to do - you might have to map between `(i,j,k)` and active index with the help of the grid class.

If you have problems - please post a script and I can take a look.

**Comment by markusdregi** [comment]
Please reopen if you need any further assistance.
