### ISSUE TITLE
Documentation of available functionalities/APIs

### ISSUE THREAD

**Issue by kudhru** [Statoil/libecl#74]
Hi

I have been trying to use the python wrapper of the libecl library for reading the .GRID and .EGRID files. Is there any documentation having a list of functionalities/ APIs supported by the libecl library? A link to useful tutorials/examples would also be very helpful.

Thanks and Regards
Dhruv

**Comment by kudhru** [comment]
Anyone ?

**Comment by pgdr** [comment]
Hello, @kudhru.  Is there anything in specific you want to achieve (that might give us some hints on what you need help with).  The list of functions is offered by python:
```python
>>> from ecl.ecl import EclGrid
>>> help(EclGrid)
...
 |  active(self, ijk=None, global_index=None)
 |      Is the cell active?
 |      
 |      See documentation og get_xyz() for explanation of parameters
 |      @ijk and @global_index.
 |  
...
 |  cell_contains(self, x, y, z, active_index=None, global_index=None, ijk=None)
 |      Will check if the cell contains point given by world
 |      coordinates (x,y,z).
 |      
 |      See method get_xyz() for documentation of @active_index,
 |      @global_index and @ijk.
...
```
etc.

For simple testing, you can try with [NORNE_ATW2013.EGRID](https://github.com/OPM/opm-data/blob/master/norne/ECL.2014.2/NORNE_ATW2013.EGRID):
```python
>>> from ecl.ecl import EclGrid
>>> norne = EclGrid('NORNE_ATW2013.EGRID')
>>> print(norne)
EclGrid("NORNE_ATW2013.EGRID", 46x112x22, global_size = 113344, active_size = 44431) at 0x31b3350
>>> norne.get_xyz(ijk=(40, 30, 20))
(458237.05610787513, 7319791.291008554, 3078.4617614746094)
>>> norne.find_cell(458237.056, 7319791.29, 3078.46)
(40, 30, 20)
```

**Comment by kudhru** [comment]
I am actually looking to extract out all the meaningful data from the .EGRID and .GRID file so that I can play around with it. 

Is there a simple way to extract out all the data from .EGRID, .GRID etc. files in a human readable format (for example, CSV format)?

**Comment by joakim-hove** [comment]
> I am actually looking to extract out all the meaningful data from the .EGRID and .GRID file so that I can play around with it. [....] Is there a simple way to extract out all the data from .EGRID, .GRID etc. files in a human readable format (for example, CSV format)?

As @pgdr said the python API is reasonably well self-described/documented, there is no method for exporting grid structure to CSV - and frankly I do consider csv a slightly weird format for grid data. Again - if you have a more specific question we can probably help you.

Roughly speaking the grid class internalizes a datastructure for all cells in the grid, you can then query things like:

1. Cell indices: `(i,j,k) <-> global_index <-> active_index`.
2. Cell geometries:
   1. Location of cell corner points and cell center.
   2. Cell volume.
3. Cell contains point `(x,y,z)` and map from `(x,y,z)` to `(i,j,k)`

Observe that if you are interested in properties like e.g. `PERMX` or solution data like `PRESSURE` you must consult the INIT and Restart files - you can use the `ecl.ecl.EclFile` class to open these files. Observe that the data in INIT and Restart files just consists of *flat vectors* - of all the *active cells* - so to interpret them you typcially also need a grid.

**Comment by kudhru** [comment]
I am basically trying to understand how Resinsight parses the files with extension .EGRID,.GRID etc. to show up the 3D view of the reservoir. Resinsight uses the libecl pacakge and hence, my question. I am following up the same on github.com/opm/resinsight#1521 . If you have any useful insights, please feel free to add!

Thanks for all the help!

Thanks
Dhruv

**Comment by joakim-hove** [comment]
> I am basically trying to understand how Resinsight parses the files with extension .EGRID,.GRID etc. to show up the 3D view of the reservoir. Resinsight uses the libecl pacakge and hence, my question. I am following up the same on github.com/OPM/ResInsight#1521 . If you have any useful insights, please feel free to add!

Well - I am still struggling a bit to understand what you are after, understanding the EGRID / GRID format is *quite low level* - that is fully implemented in the [`ecl_grid.c`](https://github.com/Statoil/libecl/blob/master/libecl/src/ecl_grid.c).

**Comment by pgdr** [comment]
> I am basically trying to understand how Resinsight parses the files [...]
Yes, `libecl` parses the EGRID files.  Are you interested in the file format itself, or the grid structure?

> with extension .EGRID,.GRID etc.
When you say "etc", what are you referring to?  Are you also interested in INIT files, restart and summary files?

**Comment by kudhru** [comment]
So, this is what I am doing currently for my research:
1. Ran the "flow" simulations using the open-source opm packages like [opm-simulators](https://github.com/OPM/opm-simulators).
2. Step 1 generates the following files: `data.DEBUG, data.param, data.EGRID, data.INIT, data.PRT, data.SMSPEC, data.UNRST, data.UNSMRY, step_timing.txt, walltime.txt `
3. I use the [summaryplot.py](https://github.com/OPM/opm-utilities/blob/master/summaryplot) script to generate 2-D plots from these output files.
4. I also need to generate 3-D models of the reservoir/grid using python. This will be similar/equivalent to how [ResInsight](https://github.com/OPM/ResInsight) generates the 3-D models. Now, [ResInsight doc](https://github.com/OPM/ResInsight#dependencies) says that they use libecl to access Eclipse result files.  My task of generating 3-D models of the grid using python will involve two steps (as I can think of):
a. Extract out the meaningful/required info from the output files (EGRID, SMSPEC, UNRST etc).
b. Plot the 3-D model using some python library.

So, currently, I am stuck at step 4 (a) above. 
I think I need to understand both - the file format as well as the grid structure! Any help would be greatly appreciated!

Let me know if any other detail is required. Sorry for the troubles!

**Comment by kudhru** [comment]
?

**Comment by markusdregi** [comment]
> I also need to generate 3-D models of the reservoir/grid using python.

I would then start by visualising the geometric structure of the grid. You can enumerate the cells of the grid using either their _global index_ or their _ijk index_. The first can be achieved as follows:
`for cell_index in range(grid.getGlobalSize()):`

Given a specific cell_index you can retrieve the cell's 8 corners by the following snippet: 
` [grid.getCellCorner(i, global_index=cell_index) for i in range(8)]`.

As explained in the documentation of _EclGrid.getCellCorner_ the order of the corners are as follows:

>    lower layer followed by upper layer:
> 
>     2---3           6---7
>     |   |           |   |
>     0---1           4---5

This should be enough to get you started. Later on, you can fetch data for various cells using their _global index_. If you for some reason fail to do so, do not hesitate to come back and ask for support regarding the data you failed to retrieve..

**Comment by pgdr** [comment]
>  [4]a. Extract out the meaningful/required info from the output files (EGRID, SMSPEC, UNRST etc).

This is a very broad description.  All the information that exists are in these files, so here's a small code to help you start (the Norne files are in [`OPM/opm-data/norne/ECL.2014.2`](https://github.com/OPM/opm-data/tree/master/norne/ECL.2014.2)):

```python
#!/usr/bin/env python
# ... GPL 3 or later ...

from ecl.ecl import EclGrid, EclInitFile, Ecl3DKW, EclSum

grid = EclGrid('NORNE_ATW2013.EGRID')
init = EclInitFile(grid, 'NORNE_ATW2013.INIT')
smry = EclSum('NORNE_ATW2013.UNSMRY')

i,j,k = 11,13,17
x,y,z = grid.getNodeXYZ(i,j,k)
print('The cell (%d,%d,%d) is located at approximately (%.2f, %.2f, %.2f)' %
      (i,j,k, x,y,z))

permx = init['PERMX'][0]
permx3d = Ecl3DKW.castFromKW(permx, grid)

print('The X-permeability in (%d,%d,%d) is %g' % (i,j,k, permx3d[i,j,k]))

print('Wells: %s' % ' '.join(smry.wells()))

```

**Comment by kudhru** [comment]
Thanks for the help, everyone.
@pgdr Is there a document explaining the file format as well as the grid structure?

**Comment by pgdr** [comment]
The grid structure is rather self-explanatory.  The file format are Eclipse files, please consult your local reservoir engineer.  Let us know if you have further issues with libecl.

**Comment by kudhru** [comment]
Ok thanks!

Regards
Dhruv
