### ISSUE TITLE
bogus cmake files get installed

### ISSUE THREAD

**Issue by blattms** [Statoil/libecl#76]
```
mblatt@loft11004:~/opt$ find libecl/include -name \*.cmake
libecl/include/ert/util/CMakeFiles/CMakeDirectoryInformation.cmake
libecl/include/ert/util/cmake_install.cmake
libecl/include/ert/util/CTestTestfile.cmake
```
Are these installed by accident? They seem to contain only information valid in the build directory.

**Comment by jokva** [comment]
Yes. I'll get rid of them.

**Comment by jokva** [comment]
https://github.com/Statoil/libecl/pull/77

Please try this patch and check if it solves your problem.

**Comment by blattms** [comment]
Yes with this PR the files are not installed anymore.

**Comment by jokva** [comment]
Excellent.
