### ISSUE TITLE
Problem dumping grid data to a csv file

### ISSUE THREAD

**Issue by gerwathome** [Statoil/libecl#79]
Hi,
When using EclSum to export grid data to a csv file, the key is of the form BPR:1,1,1.  The extra commas are troublesome when trying to read the csv file.  Is there a way to remove the commas from the key before writing the csv file?  SPE1 asks for this type of output:
```
-- 2a) Pressures of the cell where the injector and producer are located
BPR
1  1  1 /
10 10 3 /
/
```
Here is the script that I used on the SPE1 output:
```
#!/usr/bin/env python
import sys
import ert.ecl.ecl as ecl
for arg in sys.argv[1:len(sys.argv)]:
    print "dumping case %s" % arg
    case = arg
    sum_data = ecl.EclSum(case)
    sum_data.exportCSV(case + ".csv", date_format='%d-%b-%Y', sep=',')
```
I suppose a possible work around would be to change the output separator, and then post process the csv file, but it would be nicer if it could be handled within python.
Thanks for your help,
George

**Comment by joakim-hove** [comment]
Hello;

I have some suggestions/thoughts - hopefully you can use some of it:

1. You have changed the default separator from `;` to `,`, although the format is called *comma* seperated it is my impression that `;` is the most used separator. 
2. By default the `exportCSV()` method will export *all* the summary keys, but by passing the optional arguments `keys=["BPR:1", "FOPR", "FGPR"]` you will only get the keys you ask for. Observe that the block properties, i.e. `BPR` are duplicated in the summary data set, both as: `BPR:i,j,k` and as `BPR:g` where `g = i + (j-1)*nx + (k-1)*nx*ny` - so if you only use the `BPR:g`form you will get no `,`.
3. Post processing the output file .... (which can of course be done in Python).

But I am quite confident alternative 1 will actually solve your problems?! 

PS: Just a tip - you do not need to add the upper limit in the `for`loop:
```
for arg in sys.argv[1:]:
     print "Dumping case ...."
```

**Comment by pgdr** [comment]
Also, the `ert` namespace is _deprecated_, so you should simply write `from ecl.ecl import EclSum`.
```python
#!/usr/bin/env python
import sys
from ecl.ecl import EclSum
sep = ','
date_fmt = '%d-%b-%Y'
keys = ["BPR:1", "FOPR", "FGPR", "FWPR", "FWIP"]
for case in sys.argv[1:]:
    print "dumping case %s" % case
    sum_data = EclSum(case)
    print "\t%r" % sum_data
    sum_data.exportCSV(case + ".csv", date_format=date_fmt, sep=sep, keys=keys)
```

**Comment by gerwathome** [comment]
Hi,
Thanks for your suggestions. Sorry for my awkwardness with Python.  As a long time simulation engineer, dealing with long text files is a common problem where, ahem, Perl is more appropriate.
Thanks,
George

**Comment by joakim-hove** [comment]
> ahem, Perl is more appropriate.

![image](https://cloud.githubusercontent.com/assets/1321665/26374383/7503b80a-4005-11e7-88a6-67d5f0d0003b.png)

Apart from the slight language disagreements; I hope your problem was solved. I'll close this case now - but feel free to reopen/create a new if you have further concrete questions - we think these Python binding are quite good!

**Comment by gerwathome** [comment]
I agree, they are quite good.  I only meant that I am much more used to writing scripts to solve one off problems, than trying to develop generally usable software.  With your suggestions. the problem was easy this morning.  Last night my mind was too inflexible.
Thanks.
