### ISSUE TITLE
python equivalent of ecl_grid_iget_lgr

### ISSUE THREAD

**Issue by kudhru** [Statoil/libecl#82]
Hi

Is there a python equivalent of [ecl_grid_iget_lgr](https://github.com/Statoil/libecl/blob/755dadcae23a5dcbdab79d28688a87d6a1738fdc/libecl/src/ecl_grid.c#L5073)? I see that there is a python equivalent [get_lgr](https://github.com/Statoil/libecl/blob/755dadcae23a5dcbdab79d28688a87d6a1738fdc/python/python/ecl/ecl/ecl_grid.py#L910) of [ecl_grid_get_lgr](https://github.com/Statoil/libecl/blob/755dadcae23a5dcbdab79d28688a87d6a1738fdc/libecl/src/ecl_grid.c#L5019).

**Comment by joakim-hove** [comment]
No - that is not wrapped in Python; but it is in this PR: #83

**Comment by markusdregi** [comment]
I'm closing this issue as the PR is merged.
