### ISSUE TITLE
ert python in Windows

### ISSUE THREAD

**Issue by saeedfb** [Statoil/libecl#96]
Hi, 
I would like to use ERT python functions in Windows to read mainly simulation output data such as summary vectors and grid data.  What I have done so far was to put the ERT python folder in the location where python compiler knows but I have zero knowledge about building shared libraries using CMake etc. I am stuck at the first line "import ecl.ecl as ecl" because of shared libraries. Is there any easy workaround for this, like getting the libraries from somewhere. I am using windows 7 and windows 8 with python 2.7. 

Appreciate a response. 
Saeed

**Comment by jokva** [comment]
Hi, and thanks for the interest!

Using `ecl` on Windows with python is not really supported, but might incidentally work. None of our developers, or clients, use Windows, so nothing is developed for or tested much on it, unless we're using third party services like Appveyor for it. An unfortunate consequence of this is that the ecl python package on windows is neglected.

What you can try is to modify the cmake files a little bit and remove the checks that will _disable_ python on Windows, and see if that works for you. The logic should be fairly easy to follow and resides in the `python/CMakeLists.txt` file. Then, when building, pass `-DBUILD_SHARED_LIBS=ON` when you invoke cmake.

We'd be very happy if you'd test and maybe even help us develop `ecl` for Windows, but for now we cannot immediately guarantee that it works.

May I ask what exactly you want to accomplish? We have several small command line tools that might be able to accomplish what you want, if it's about just reading some summary vectors.

**Comment by saeedfb** [comment]
Thanks for the quick reply. For starters, I would like to read summary vectors from simulation runs and to read grid data (porosity, perm, saturation, etc). I do appreciate if I could get a solution using ERT.

**Comment by jokva** [comment]
Ok. Tell you what, let me get back to you Tuesday, and I'll see if we can get something up and running really fast. I'm not sure if it'll work at all, but it's worth a try. Other than that experiment I cannot guarantee we'd be able to allocate resources for Windows support with python, as it's just not a priority for us, since none of our clients use it.

**Comment by saeedfb** [comment]
I highly appreciate it.

**Comment by pgdr** [comment]
I know this is not the answer you're looking for, but if you need something quick, then it's quite easy to set up a virtual machine with, e.g. Ubuntu 14.04 and install `ecl` on that.  You can also share disk areas, so you can read and write files from your Windows storage.

**Comment by saeedfb** [comment]
When it comes to unix Im illiterate. But thanks for the solution. I just
need something quick mainly for reading summary and grid files.

**Comment by markusdregi** [comment]
Please reopen this issue if you need any more assistance.

**Comment by saeedfb** [comment]
Well, Im just waiting for Joakim if something fast to read summary data can
be prepared. Do appreciate the time and effort you are putting on this as
its not your priority.

**Comment by jokva** [comment]
Hi,

I wasn't able to get quick windows support up and running, so I won't be able to send you a binary I'm afraid.

**Comment by saeedfb** [comment]
Ok. Thanks anyway for your time and good luck in developing ERT further.

**Comment by jokva** [comment]
You're of course welcome, sorry we couldn't help.
